version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    ports:
      - "3000:3000"   # Backend accessible sur localhost:3000
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=bystalindrive
      - DB_PORT=3306
      - JWT_SECRET=myUltraSecretKeyForJWT
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: frontend_container
    restart: always
    ports:
      - "3001:80"   # Frontend accessible sur localhost:3001
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bystalindrive
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: