version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    ports:
      - "5001:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=rootpassword     # <- même que MYSQL_ROOT_PASSWORD
      - DB_NAME=bystalindrive
      - DB_PORT=3306
      - JWT_SECRET=myUltraSecretKeyForJWT
    depends_on:
      - db
    command: sh -c "wait-for-it db:3306 -- node server.js"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: frontend_container
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword    # <- mot de passe root
      MYSQL_DATABASE: bystalindrive        # <- base créée automatiquement
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: